# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.disqus_extension:
        class: AppBundle\Twig\DisqusExtension
        public: false
        arguments: ["@twig", "@router.default", "@security.token_storage", "%disqus%"]
        tags:
            - { name: twig.extension }
